# Puerto donde correrá este microservicio (distinto al clásico 8080 para evitar choques)
server.port=8081

# Nombre del microservicio
spring.application.name=ms-usuarios

# Configuración de conexión a tu PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuarios
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA (Hibernate)
# 'update' creará las tablas automáticamente basándose en tu código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect